name: CI
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '**/.github/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v23
        with:
          node-version: '16.x'
      - name: Install npm modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
  build:
    needs: ['lint']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install npm modules
        run: npm install
      - name: Build package
        run: npm run build

